"""initial workflow tables

Revision ID: 2c11295370e2
Revises: 
Create Date: 2026-07-02 17:22:04.225757
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2c11295370e2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_name', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('new_product_opportunity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_sheet', sa.String(length=128), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('batch', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('site', sa.String(length=32), nullable=True),
    sa.Column('developer_department', sa.String(length=128), nullable=True),
    sa.Column('developer_name', sa.String(length=128), nullable=True),
    sa.Column('category_level1', sa.String(length=128), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('main_sku_name', sa.String(length=255), nullable=True),
    sa.Column('main_sku', sa.String(length=128), nullable=False),
    sa.Column('sub_sku_name', sa.String(length=255), nullable=True),
    sa.Column('sub_sku', sa.String(length=128), nullable=False),
    sa.Column('product_type', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('current_status', sa.String(length=64), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_file', 'source_sheet', 'source_row', name='uq_opportunity_source_row')
    )
    op.create_index(op.f('ix_new_product_opportunity_main_sku'), 'new_product_opportunity', ['main_sku'], unique=False)
    op.create_index(op.f('ix_new_product_opportunity_sub_sku'), 'new_product_opportunity', ['sub_sku'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('receiver_user_id', sa.String(length=36), nullable=True),
    sa.Column('receiver_name', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('message_title', sa.String(length=255), nullable=False),
    sa.Column('send_status', sa.String(length=64), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_notification_dedupe_key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dingtalk_user_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dingtalk_user_id')
    )
    op.create_table('arrival_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse', sa.String(length=128), nullable=True),
    sa.Column('arrived_quantity', sa.Integer(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('listing_status', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['new_product_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_instance',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('current_node', sa.String(length=64), nullable=False),
    sa.Column('current_status', sa.String(length=64), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=True),
    sa.Column('owner_role', sa.String(length=64), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['new_product_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('four_week_summary',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('summary_user', sa.String(length=128), nullable=True),
    sa.Column('achieved', sa.Boolean(), nullable=True),
    sa.Column('out_of_stock_impact', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['new_product_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_research_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('research_type', sa.String(length=64), nullable=False),
    sa.Column('competitor_url', sa.Text(), nullable=True),
    sa.Column('competitor_price', sa.Float(), nullable=True),
    sa.Column('competitor_monthly_sales', sa.Float(), nullable=True),
    sa.Column('reference_daily_sales', sa.Float(), nullable=True),
    sa.Column('reference_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['new_product_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_record',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_user_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_name', sa.String(length=128), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['new_product_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_mapping',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('dingtalk_user_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('group_name', sa.String(length=128), nullable=True),
    sa.Column('site', sa.String(length=32), nullable=True),
    sa.Column('manager_user_id', sa.String(length=36), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_claim_forecast',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('group_name', sa.String(length=128), nullable=True),
    sa.Column('salesperson_name', sa.String(length=128), nullable=True),
    sa.Column('claim_result', sa.String(length=32), nullable=True),
    sa.Column('claim_daily_sales', sa.Float(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('feedback_summary', sa.Text(), nullable=True),
    sa.Column('source_column', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['new_product_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_record_snapshot',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_sheet', sa.String(length=128), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('column_range', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['new_product_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocking_request',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('request_type', sa.String(length=64), nullable=False),
    sa.Column('salesperson_name', sa.String(length=128), nullable=True),
    sa.Column('main_sku', sa.String(length=128), nullable=True),
    sa.Column('sub_sku', sa.String(length=128), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('unit_volume', sa.Float(), nullable=True),
    sa.Column('daily_sales', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('warehouse', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['new_product_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_chain_quote',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('quote_user', sa.String(length=128), nullable=True),
    sa.Column('quote_comment', sa.Text(), nullable=True),
    sa.Column('suggested_purchase_price', sa.Float(), nullable=True),
    sa.Column('developer_acceptance', sa.String(length=64), nullable=True),
    sa.Column('quoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['new_product_opportunity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_task',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('flow_instance_id', sa.String(length=36), nullable=False),
    sa.Column('node_code', sa.String(length=64), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('assignee_user_id', sa.String(length=36), nullable=True),
    sa.Column('assignee_name', sa.String(length=128), nullable=True),
    sa.Column('assignee_role', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dingtalk_todo_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['flow_instance_id'], ['flow_instance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flow_task')
    op.drop_table('supply_chain_quote')
    op.drop_table('stocking_request')
    op.drop_table('source_record_snapshot')
    op.drop_table('sales_claim_forecast')
    op.drop_table('role_mapping')
    op.drop_table('review_record')
    op.drop_table('market_research_item')
    op.drop_table('four_week_summary')
    op.drop_table('flow_instance')
    op.drop_table('arrival_record')
    op.drop_table('users')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_new_product_opportunity_sub_sku'), table_name='new_product_opportunity')
    op.drop_index(op.f('ix_new_product_opportunity_main_sku'), table_name='new_product_opportunity')
    op.drop_table('new_product_opportunity')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
