"""add import and export batches

Revision ID: 7aaf1f78c47d
Revises: 2c11295370e2
Create Date: 2026-07-03 09:31:08.131065
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7aaf1f78c47d'
down_revision: str | None = '2c11295370e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_batch',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('exported_by', sa.String(length=128), nullable=True),
    sa.Column('exported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batch',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_sheet', sa.String(length=128), nullable=True),
    sa.Column('imported_by', sa.String(length=128), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_row',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('export_batch_id', sa.String(length=36), nullable=False),
    sa.Column('opportunity_id', sa.String(length=36), nullable=False),
    sa.Column('claim_record_id', sa.String(length=36), nullable=True),
    sa.Column('salesperson_name', sa.String(length=128), nullable=True),
    sa.Column('main_sku', sa.String(length=128), nullable=False),
    sa.Column('sub_sku', sa.String(length=128), nullable=False),
    sa.Column('claim_daily_sales', sa.Float(), nullable=False),
    sa.Column('stocking_quantity', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('warehouse', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_record_id'], ['sales_claim_forecast.id'], name='fk_export_row_claim_record_id'),
    sa.ForeignKeyConstraint(['export_batch_id'], ['export_batch.id'], name='fk_export_row_export_batch_id'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['new_product_opportunity.id'], name='fk_export_row_opportunity_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('new_product_opportunity') as batch_op:
        batch_op.add_column(sa.Column('import_batch_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_new_product_opportunity_import_batch_id', 'import_batch', ['import_batch_id'], ['id'])
    with op.batch_alter_table('source_record_snapshot') as batch_op:
        batch_op.add_column(sa.Column('import_batch_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_source_record_snapshot_import_batch_id', 'import_batch', ['import_batch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_record_snapshot') as batch_op:
        batch_op.drop_constraint('fk_source_record_snapshot_import_batch_id', type_='foreignkey')
        batch_op.drop_column('import_batch_id')
    with op.batch_alter_table('new_product_opportunity') as batch_op:
        batch_op.drop_constraint('fk_new_product_opportunity_import_batch_id', type_='foreignkey')
        batch_op.drop_column('import_batch_id')
    op.drop_table('export_row')
    op.drop_table('import_batch')
    op.drop_table('export_batch')
    # ### end Alembic commands ###
