OPPORTUNITY_PENDING_ASSIGNMENT = "pending_assignment"
OPPORTUNITY_OPEN_CLAIM_POOL = "open_claim_pool"
OPPORTUNITY_ASSIGNED = "assigned"
OPPORTUNITY_CLAIM_SUBMITTED = "claim_submitted"
OPPORTUNITY_CLAIM_REJECTED = "claim_rejected"
OPPORTUNITY_READY_FOR_STOCKING = "ready_for_stocking"
OPPORTUNITY_WAITING_ARRIVAL = "waiting_arrival"
OPPORTUNITY_CONFIRMED_NOT_CLAIM = "已确认不认领"
OPPORTUNITY_RETURNED_FOR_SUPPLEMENT = "returned_for_supplement"
OPPORTUNITY_DISABLED = "disabled"
OPPORTUNITY_REPLACED_BY_NORMALIZED_SELECTION1 = "replaced_by_normalized_selection1"

CLAIM_WAITING_ARRIVAL = "waiting_arrival"
CLAIM_WAITING_EXPORT = "waiting_export"
CLAIM_WAITING_STOCKING_REQUEST = "waiting_stocking_request"
CLAIM_STOCKING_PAUSED = "stocking_paused"
CLAIM_WAITING_SECONDARY_RESEARCH = "waiting_secondary_research"
CLAIM_WAITING_LISTING = "waiting_listing"
CLAIM_LISTING_OBSERVATION = "listing_observation"
CLAIM_DISABLED = "disabled"

CLAIM_RESULT_CLAIM = "claim"
CLAIM_RESULT_REJECT = "reject"

REVIEW_PENDING = "review_pending"
REVIEW_APPROVED = "approved"
REVIEW_CONFIRMED_NOT_CLAIM = "confirmed_not_claim"
REVIEW_RETURNED_FOR_SUPPLEMENT = "returned_for_supplement"

TASK_PENDING = "pending"
TASK_COMPLETED = "completed"
